name: Update YouTube Video List

on:
  schedule:
    # Run every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update_video_list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Fetch YouTube Videos
        uses: actions/github-script@v5
        with:
          script: |
            const fetch = require('node-fetch');
            const { createOrUpdateFile } = require('@actions/utils');

            // Extract channel ID from YouTube link
            const channelLink = 'https://www.youtube.com/channel/UC52FbJvOtKytDuiZJP8St8Q';
            const channelID = channelLink.split('/').slice(-1)[0];

            const apiKey = process.env.YOUTUBE_API_KEY;
            const url = `https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=${channelID}&key=${apiKey}&maxResults=5&type=video`;

            const response = await fetch(url);
            const data = await response.json();

            const videoList = data.items.map(item => ({
              title: item.snippet.title,
              videoId: item.id.videoId,
              thumbnail: item.snippet.thumbnails.default.url,
              publishedAt: item.snippet.publishedAt
            }));

            await createOrUpdateFile('youtube_videos.json', JSON.stringify(videoList, null, 2));
